### ISSUE TITLE
Crash Thermal Expansion

### ISSUE THREAD

**Issue by Sang-bin** [Stumblinbear/BetterRecords#34]
[23:57:59] [Client thread/ERROR] [FML]: Caught exception from Thermal Expansion (thermalexpansion)
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.codingforcookies.betterrecords.crafting.recipe.RecipeMultiRecord.func_77569_a, parameter worldIn
	at com.codingforcookies.betterrecords.crafting.recipe.RecipeMultiRecord.func_77569_a(RecipeMultiRecord.kt) ~[RecipeMultiRecord.class:?]
	at cofh.lib.util.helpers.ItemHelper.findMatchingRecipe(ItemHelper.java:306) ~[ItemHelper.class:?]
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.addAllLogs(SawmillManager.java:280) ~[SawmillManager.class:?]
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.loadRecipes(SawmillManager.java:194) ~[SawmillManager.class:?]
	at cofh.thermalexpansion.util.managers.machine.SawmillManager.initialize(SawmillManager.java:189) ~[SawmillManager.class:?]
	at cofh.thermalexpansion.ThermalExpansion.managerInitialize(ThermalExpansion.java:167) ~[ThermalExpansion.class:?]
	at cofh.thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:110) ~[ThermalExpansion.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) ~[forge-1.10.2-12.18.3.2511.jar:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:561) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:58:00] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  PlusTiC (plustic-5.2.1.2.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.7.0.124.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.12.130-universal.jar)
  SpongeCoremod (spongeforge-1.10.2-2477-5.2.0-BETA-2698.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3 (1).jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

**Comment by NicholasFeldman** [comment]
Second crashlog from @Ouack23: https://pastebin.com/tWa111gT

**Comment by NicholasFeldman** [comment]
The fix has been released, and is awaiting CurseForge's approval:
https://minecraft.curseforge.com/projects/better-records/files/2499608
